<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bibaket.Application\Bibaket.Application.csproj" />
    <ProjectReference Include="..\Bibaket.Domin\Bibaket.Domain.csproj" />
    <ProjectReference Include="..\Bibaket.Ifra.Data\Bibaket.Ifra.Data.csproj" />
  </ItemGroup>

</Project>
